version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - build

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    labels:
      - build
