version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '00:00'
      timezone: Europe/Berlin
    assignees:
      - mrsmrynk
    reviewers:
      - mrsmrynk
    labels:
      - build

  - package-ecosystem: pip
    directory: /dev
    schedule:
      interval: weekly
      day: monday
      time: '00:00'
      timezone: Europe/Berlin
    assignees:
      - mrsmrynk
    reviewers:
      - mrsmrynk
    labels:
      - build
