changelog:
  exclude:
    authors:
      - dependabot
    labels:
      - ignore for release
  categories:
    - title: New Features
      labels:
        - feat
    - title: Bug Fixes
      labels:
        - fix
    - title: Breaking Changes
      labels:
        - breaking
    - title: Other Changes
      labels:
        - '*'
