site_name: aviary
site_url: https://geospaitial-lab.github.io/aviary
repo_name: geospaitial-lab/aviary
repo_url: https://www.github.com/geospaitial-lab/aviary
docs_dir: ../docs
exclude_docs: README.md

nav:
  - Get started: index.md
  - How-to Guides:
    - How-to Guides: how_to_guides/index.md
    - Installation:
      - How to install aviary with pip: how_to_guides/installation/how_to_install_aviary_with_pip.md
      - How to install aviary with uv: how_to_guides/installation/how_to_install_aviary_with_uv.md
      - How to install aviary with Docker: how_to_guides/installation/how_to_install_aviary_with_docker.md
    - API:
      - How to use the bounding box: how_to_guides/api/how_to_use_the_bounding_box.md
      - How to use the process area: how_to_guides/api/how_to_use_the_process_area.md
    - CLI:
      - How to run the segmentation pipeline: how_to_guides/cli/how_to_run_the_segmentation_pipeline.md
      - How to run the postprocessing pipeline: how_to_guides/cli/how_to_run_the_postprocessing_pipeline.md
  - API Reference:
    - API Reference: api_reference/index.md
    - aviary:
      - BoundingBox: api_reference/core/bounding_box.md
      - Channel:
        - Channel: api_reference/core/channel/channel.md
        - RasterChannel: api_reference/core/channel/raster_channel.md
        - VectorChannel: api_reference/core/channel/vector_channel.md
      - Enums: api_reference/core/enums.md
      - Exceptions: api_reference/core/exceptions.md
      - Grid: api_reference/core/grid.md
      - Tiles: api_reference/core/tiles.md
      - Type Aliases: api_reference/core/type_aliases.md
    - aviary.inference:
      - TileFetcher:
          - TileFetcher: api_reference/inference/tile_fetcher/tile_fetcher.md
          - CompositeFetcher: api_reference/inference/tile_fetcher/composite_fetcher.md
          - VRTFetcher: api_reference/inference/tile_fetcher/vrt_fetcher.md
          - WMSFetcher: api_reference/inference/tile_fetcher/wms_fetcher.md
      - TileLoader: api_reference/inference/tile_loader.md
      - TileSet: api_reference/inference/tile_set.md
      - TilesExporter:
          - GridExporter: api_reference/inference/tiles_exporter/grid_exporter.md
          - VectorExporter: api_reference/inference/tiles_exporter/vector_exporter.md
      - TilesProcessor:
          - TilesProcessor: api_reference/inference/tiles_processor/tiles_processor.md
          - CopyProcessor: api_reference/inference/tiles_processor/copy_processor.md
          - NormalizeProcessor: api_reference/inference/tiles_processor/normalize_processor.md
          - ParallelCompositeProcessor: api_reference/inference/tiles_processor/parallel_composite_processor.md
          - RemoveBufferProcessor: api_reference/inference/tiles_processor/remove_buffer_processor.md
          - RemoveProcessor: api_reference/inference/tiles_processor/remove_processor.md
          - SelectProcessor: api_reference/inference/tiles_processor/select_processor.md
          - SequentialCompositeProcessor: api_reference/inference/tiles_processor/sequential_composite_processor.md
          - StandardizeProcessor: api_reference/inference/tiles_processor/standardize_processor.md
          - VectorizeProcessor: api_reference/inference/tiles_processor/vectorize_processor.md
    - aviary.pipeline:
      - PostprocessingPipeline: api_reference/pipeline/postprocessing_pipeline.md
      - SegmentationPipeline: api_reference/pipeline/segmentation_pipeline.md
    - aviary.utils:
        - CoordinatesFilter:
            - CoordinatesFilter: api_reference/utils/coordinates_filter/coordinates_filter.md
            - CompositeFilter: api_reference/utils/coordinates_filter/composite_filter.md
            - DuplicatesFilter: api_reference/utils/coordinates_filter/duplicates_filter.md
            - GeospatialFilter: api_reference/utils/coordinates_filter/geospatial_filter.md
            - MaskFilter: api_reference/utils/coordinates_filter/mask_filter.md
            - SetFilter: api_reference/utils/coordinates_filter/set_filter.md
  - CLI Reference:
      - CLI Reference: cli_reference/index.md
      - Segmentation pipeline: cli_reference/segmentation_pipeline.md
      - Postprocessing pipeline: cli_reference/postprocessing_pipeline.md
  - Aviary:
      - Aviary: aviary/index.md

theme:
  name: material
  custom_dir: ../docs/overrides
  language: en
  logo_light_mode: assets/aviary_logo_black.svg
  logo_dark_mode: assets/aviary_logo_white.svg
  favicon: assets/aviary_logo_white.svg
  font:
    text: Noto Sans
    code: Noto Sans Mono
  icon:
    repo: simple/github
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: white
      accent: custom
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: custom
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

plugins:
  - privacy
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            show_root_full_path: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: source
            docstring_style: google
            docstring_section_style: spacy
            merge_init_into_class: true
            show_docstring_raises: false
            annotations_path: source
            show_signature: false
            show_overloads: false
          paths:
            - ../

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      anchorlink: true
      title: On this page

extra:
  consent:
    title: Privacy consent
    description: |
      We use third-party services (but <strong>no cookies</strong>)
      to improve the documentation and the user experience.<br />
      You can change the privacy settings at any time.
      Have a look at our privacy policy for further information.
    cookies:
      github: |
        <a href="https://www.github.com" target="_blank" rel="noopener noreferrer">GitHub</a>
        for repository information
      maps: |
        <a href="https://www.openstreetmap.org" target="_blank" rel="noopener noreferrer">OpenStreetMap</a>
        and <a href="https://www.bezreg-koeln.nrw.de/geobasis-nrw" target="_blank" rel="noopener noreferrer">Geobasis NRW</a>
        for interactive maps
    actions:
      - accept
      - reject
      - manage
  generator: false
  social:
    - icon: simple/github
      link: https://www.github.com/geospaitial-lab
    - icon: simple/huggingface
      link: https://www.huggingface.co/geospaitial-lab

extra_css:
  - stylesheets/color.css
  - stylesheets/extra.css

extra_javascript:
  - javascripts/consent.js
  - javascripts/open_links_in_new_tab.js

extra_templates:
  - how_to_guides/api/maps/bounding_box.html
  - how_to_guides/api/maps/bounding_box_buffer_positive.html
  - how_to_guides/api/maps/bounding_box_buffer_negative.html
  - how_to_guides/api/maps/bounding_box_from_gdf.html
  - how_to_guides/api/maps/bounding_box_from_gdf_districts.html
  - how_to_guides/api/maps/bounding_box_quantize.html
  - how_to_guides/api/maps/bounding_box_setter.html
  - how_to_guides/api/maps/process_area.html
  - how_to_guides/api/maps/process_area_add.html
  - how_to_guides/api/maps/process_area_and.html
  - how_to_guides/api/maps/process_area_append.html
  - how_to_guides/api/maps/process_area_filter_difference.html
  - how_to_guides/api/maps/process_area_filter_intersection.html
  - how_to_guides/api/maps/process_area_from_bounding_box.html
  - how_to_guides/api/maps/process_area_from_bounding_box_quantize.html
  - how_to_guides/api/maps/process_area_from_bounding_box_tile_size.html
  - how_to_guides/api/maps/process_area_from_gdf.html
  - how_to_guides/api/maps/process_area_from_gdf_districts.html
  - how_to_guides/api/maps/process_area_setter.html
  - how_to_guides/api/maps/process_area_sub.html

copyright:
  © 2025 geospaitial lab
