site_name: aviary
site_url: https://geospaitial-lab.github.io/aviary
repo_name: geospaitial-lab/aviary
repo_url: https://www.github.com/geospaitial-lab/aviary
docs_dir: ../docs
exclude_docs: README.md

nav:
  - Get Started: index.md
  - How-to Guides:
    - How-to Guides: how_to_guides/index.md
    - API:
      - How to implement your own component: how_to_guides/api/how_to_implement_your_own_component.md
    - CLI:
      - How to register your own component: how_to_guides/cli/how_to_register_your_own_component.md
    - Installation:
      - How to install aviary with pip: how_to_guides/installation/how_to_install_aviary_with_pip.md
      - How to install aviary with uv: how_to_guides/installation/how_to_install_aviary_with_uv.md
      - How to install aviary with Docker: how_to_guides/installation/how_to_install_aviary_with_docker.md
  - API Reference:
    - API Reference: api_reference/index.md
    - aviary:
      - BoundingBox: api_reference/core/bounding_box.md
      - Channel:
        - Channel: api_reference/core/channel/channel.md
        - RasterChannel: api_reference/core/channel/raster_channel.md
        - VectorChannel: api_reference/core/channel/vector_channel.md
      - Enums: api_reference/core/enums.md
      - Exceptions: api_reference/core/exceptions.md
      - Grid: api_reference/core/grid.md
      - Tiles: api_reference/core/tiles.md
      - Type Aliases: api_reference/core/type_aliases.md
      - Vector: api_reference/core/vector.md
      - VectorLayer: api_reference/core/vector_layer.md
    - aviary.tile:
      - Model:
          - Adois: api_reference/tile/model/adois.md
      - TileFetcher:
          - TileFetcher: api_reference/tile/tile_fetcher/tile_fetcher.md
          - CompositeFetcher: api_reference/tile/tile_fetcher/composite_fetcher.md
          - VRTFetcher: api_reference/tile/tile_fetcher/vrt_fetcher.md
          - WMSFetcher: api_reference/tile/tile_fetcher/wms_fetcher.md
      - TileLoader: api_reference/tile/tile_loader.md
      - TileSet: api_reference/tile/tile_set.md
      - TilesExporter:
          - GridExporter: api_reference/tile/tiles_exporter/grid_exporter.md
          - VectorExporter: api_reference/tile/tiles_exporter/vector_exporter.md
      - TilesProcessor:
          - TilesProcessor: api_reference/tile/tiles_processor/tiles_processor.md
          - CopyProcessor: api_reference/tile/tiles_processor/copy_processor.md
          - NormalizeProcessor: api_reference/tile/tiles_processor/normalize_processor.md
          - ParallelCompositeProcessor: api_reference/tile/tiles_processor/parallel_composite_processor.md
          - RemoveBufferProcessor: api_reference/tile/tiles_processor/remove_buffer_processor.md
          - RemoveProcessor: api_reference/tile/tiles_processor/remove_processor.md
          - SelectProcessor: api_reference/tile/tiles_processor/select_processor.md
          - SequentialCompositeProcessor: api_reference/tile/tiles_processor/sequential_composite_processor.md
          - StandardizeProcessor: api_reference/tile/tiles_processor/standardize_processor.md
          - VectorizeProcessor: api_reference/tile/tiles_processor/vectorize_processor.md
    - aviary.pipeline:
      - TilePipeline: api_reference/pipeline/tile_pipeline.md
    - aviary.utils:
        - CoordinatesFilter:
            - CoordinatesFilter: api_reference/utils/coordinates_filter/coordinates_filter.md
            - CompositeFilter: api_reference/utils/coordinates_filter/composite_filter.md
            - DuplicatesFilter: api_reference/utils/coordinates_filter/duplicates_filter.md
            - GeospatialFilter: api_reference/utils/coordinates_filter/geospatial_filter.md
            - MaskFilter: api_reference/utils/coordinates_filter/mask_filter.md
            - SetFilter: api_reference/utils/coordinates_filter/set_filter.md
    - aviary.vector:
      - VectorExporter: api_reference/vector/vector_exporter.md
      - VectorLoader:
          - VectorLoader: api_reference/vector/vector_loader/vector_loader.md
          - CompositeLoader: api_reference/vector/vector_loader/composite_loader.md
          - GPKGLoader: api_reference/vector/vector_loader/gpkg_loader.md
      - VectorProcessor:
          - VectorProcessor: api_reference/vector/vector_processor/vector_processor.md
          - CopyProcessor: api_reference/vector/vector_processor/copy_processor.md
          - ParallelCompositeProcessor: api_reference/vector/vector_processor/parallel_composite_processor.md
          - RemoveProcessor: api_reference/vector/vector_processor/remove_processor.md
          - SelectProcessor: api_reference/vector/vector_processor/select_processor.md
          - SequentialCompositeProcessor: api_reference/vector/vector_processor/sequential_composite_processor.md
  - CLI Reference:
    - CLI Reference: cli_reference/index.md
    - aviary: cli_reference/aviary.md
    - aviary components: cli_reference/aviary_components.md
    - aviary docs: cli_reference/aviary_docs.md
    - aviary github: cli_reference/aviary_github.md
    - aviary plugins: cli_reference/aviary_plugins.md
    - aviary tile-pipeline:
        - tile-pipeline: cli_reference/aviary_tile_pipeline/tile_pipeline.md
        - tile-pipeline components: cli_reference/aviary_tile_pipeline/tile_pipeline_components.md
        - tile-pipeline config: cli_reference/aviary_tile_pipeline/tile_pipeline_config.md
        - tile-pipeline init: cli_reference/aviary_tile_pipeline/tile_pipeline_init.md
        - tile-pipeline plugins: cli_reference/aviary_tile_pipeline/tile_pipeline_plugins.md
        - tile-pipeline run: cli_reference/aviary_tile_pipeline/tile_pipeline_run.md
        - tile-pipeline validate: cli_reference/aviary_tile_pipeline/tile_pipeline_validate.md
    - Environment Variables: cli_reference/environment_variables.md

not_in_nav: |
  legal_notice.md
  privacy_policy.md

theme:
  name: material
  custom_dir: ../docs/overrides
  language: en
  logo_light_mode: assets/aviary_logo_black.svg
  logo_dark_mode: assets/aviary_logo_white.svg
  favicon: assets/aviary_logo_white.svg
  font:
    text: Inter
    code: JetBrains Mono
  icon:
    admonition:
      abstract: material/run-fast
    repo: simple/github
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: white
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

plugins:
  - privacy
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            show_root_full_path: false
            heading_level: 3
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: source
            docstring_style: google
            docstring_section_style: spacy
            merge_init_into_class: true
            show_docstring_raises: false
            annotations_path: source
            show_signature: false
            show_overloads: false
          paths:
            - ../

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      anchorlink: true
      title: On this page

extra:
  consent:
    title: Privacy Consent
    description: |
      We use third-party services (but <strong>no cookies</strong>)
      to improve the documentation and the user experience.<br />
      You can change the privacy settings at any time.
      Have a look at our privacy policy for further information.
    cookies:
      github: |
        <a href="https://www.github.com" target="_blank" rel="noopener noreferrer">GitHub</a>
        for repository information
      maps: |
        <a href="https://www.openstreetmap.org" target="_blank" rel="noopener noreferrer">OpenStreetMap</a>
        and <a href="https://www.bezreg-koeln.nrw.de/geobasis-nrw" target="_blank" rel="noopener noreferrer">Geobasis NRW</a>
        for interactive maps
    actions:
      - accept
      - reject
      - manage
  generator: false
  social:
    - icon: simple/matrix
      link: https://matrix.to/#/#geospaitial-lab-aviary:matrix.org

extra_css:
  - stylesheets/color.css
  - stylesheets/extra.css

extra_javascript:
  - javascripts/consent.js
  - javascripts/open_links_in_new_tab.js

copyright:
  © 2025 geospaitial lab
