site_name: aviary
site_url: https://geospaitial-lab.github.io/aviary
repo_name: geospaitial-lab/aviary
repo_url: https://github.com/geospaitial-lab/aviary
docs_dir: ../docs

nav:
  - Get started: index.md
  - API Reference:
    - aviary:
      - BoundingBox: api_reference/bounding_box.md
      - Enums: api_reference/enums.md
      - ProcessArea: api_reference/process_area.md
      - Types: api_reference/types.md
    - aviary.data:
      - DataFetcher: api_reference/data/data_fetcher.md
      - DataLoader: api_reference/data/data_loader.md
      - DataPreprocessor: api_reference/data/data_preprocessor.md
      - Dataset: api_reference/data/dataset.md
    - aviary.geodata:
      - CoordinatesFilter: api_reference/geodata/coordinates_filter.md
      - GeodataPostprocessor: api_reference/geodata/geodata_postprocessor.md
      - GridGenerator: api_reference/geodata/grid_generator.md
    - aviary.inference:
      - Exporter: api_reference/inference/exporter.md
      - Model: api_reference/inference/model.md
    - aviary.pipeline:
      - SegmentationPipeline: api_reference/pipeline/segmentation_pipeline.md

theme:
  name: material
  language: en
  logo: assets/aviary_logo_white.svg
  favicon: assets/aviary_logo_white.svg
  icon:
    repo: simple/github
  font:
    text: Noto Sans
    code: Noto Sans Mono
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.expand
    - navigation.tabs
    - navigation.top
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            show_root_full_path: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: source
            docstring_style: google
            docstring_section_style: spacy
            merge_init_into_class: true
            annotations_path: source
            show_signature: false
          paths:
            - ../

extra:
  generator: false
  social:
    - icon: simple/github
      link: https://github.com/geospaitial-lab
    - icon: simple/huggingface
      link: https://huggingface.co/geospaitial-lab

copyright:
  © 2024 geospaitial lab
