site_name: aviary
site_url: https://geospaitial-lab.github.io/aviary
docs_dir: ../docs

nav:
  - Get started: index.md
  - How-to Guides:
    - How-to Guides: how_to_guides/index.md
    - Installation:
      - How to install aviary with venv: how_to_guides/installation/how_to_install_aviary_with_venv.md
      - How to install aviary with Docker: how_to_guides/installation/how_to_install_aviary_with_docker.md
  - API Reference:
    - API Reference: api_reference/index.md
    - aviary:
      - BoundingBox: api_reference/bounding_box.md
      - Enums: api_reference/enums.md
      - Exceptions: api_reference/exceptions.md
      - ProcessArea: api_reference/process_area.md
      - Types: api_reference/types.md
    - aviary.data:
      - DataFetcher: api_reference/data/data_fetcher.md
      - DataLoader: api_reference/data/data_loader.md
      - DataPreprocessor: api_reference/data/data_preprocessor.md
      - Dataset: api_reference/data/dataset.md
    - aviary.geodata:
      - CoordinatesFilter: api_reference/geodata/coordinates_filter.md
      - GeodataPostprocessor: api_reference/geodata/geodata_postprocessor.md
      - GridGenerator: api_reference/geodata/grid_generator.md
    - aviary.inference:
      - Exporter: api_reference/inference/exporter.md
      - Model: api_reference/inference/model.md
    - aviary.pipeline:
      - PostprocessingPipeline: api_reference/pipeline/postprocessing_pipeline.md
      - SegmentationPipeline: api_reference/pipeline/segmentation_pipeline.md

theme:
  name: material
  custom_dir: ../docs/overrides
  language: en
  logo_light_mode: assets/aviary_logo_black.svg
  logo_dark_mode: assets/aviary_logo_white.svg
  favicon: assets/aviary_logo_white.svg
  font:
    text: Noto Sans
    code: Noto Sans Mono
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.top
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            show_root_full_path: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: source
            docstring_style: google
            docstring_section_style: spacy
            merge_init_into_class: true
            annotations_path: source
            show_signature: false
          paths:
            - ../

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra:
  generator: false
  social:
    - icon: simple/github
      link: https://github.com/geospaitial-lab
    - icon: simple/huggingface
      link: https://huggingface.co/geospaitial-lab

extra_css:
  - stylesheets/extra.css

copyright:
  © 2024 geospaitial lab
