site_name: aviary
site_url: https://geospaitial-lab.github.io/aviary
repo_name: geospaitial-lab/aviary
repo_url: https://github.com/geospaitial-lab/aviary
docs_dir: ../docs
exclude_docs: README.md

nav:
  - Get started: index.md
  - How-to Guides:
    - How-to Guides: how_to_guides/index.md
    - Installation:
      - How to install aviary with pip: how_to_guides/installation/how_to_install_aviary_with_pip.md
      - How to install aviary with Docker: how_to_guides/installation/how_to_install_aviary_with_docker.md
    - API:
      - How to use the bounding box: how_to_guides/api/how_to_use_the_bounding_box.md
      - How to use the process area: how_to_guides/api/how_to_use_the_process_area.md
    - CLI:
      - How to run the segmentation pipeline: how_to_guides/cli/how_to_run_the_segmentation_pipeline.md
      - How to run the postprocessing pipeline: how_to_guides/cli/how_to_run_the_postprocessing_pipeline.md
  - API Reference:
    - API Reference: api_reference/index.md
    - aviary:
      - BoundingBox: api_reference/bounding_box.md
      - Enums: api_reference/enums.md
      - Exceptions: api_reference/exceptions.md
      - ProcessArea: api_reference/process_area.md
      - Types: api_reference/types.md
    - aviary.data:
      - DataFetcher:
        - DataFetcher: api_reference/data/data_fetcher/data_fetcher.md
        - CompositeFetcher: api_reference/data/data_fetcher/composite_fetcher.md
        - VRTFetcher: api_reference/data/data_fetcher/vrt_fetcher.md
        - WMSFetcher: api_reference/data/data_fetcher/wms_fetcher.md
      - DataLoader: api_reference/data/data_loader.md
      - DataPreprocessor:
        - DataPreprocessor: api_reference/data/data_preprocessor/data_preprocessor.md
        - CompositePreprocessor: api_reference/data/data_preprocessor/composite_preprocessor.md
        - NormalizePreprocessor: api_reference/data/data_preprocessor/normalize_preprocessor.md
        - StandardizePreprocessor: api_reference/data/data_preprocessor/standardize_preprocessor.md
      - Dataset: api_reference/data/dataset.md
    - aviary.geodata:
      - CoordinatesFilter:
        - CoordinatesFilter: api_reference/geodata/coordinates_filter/coordinates_filter.md
        - CompositeFilter: api_reference/geodata/coordinates_filter/composite_filter.md
        - DuplicatesFilter: api_reference/geodata/coordinates_filter/duplicates_filter.md
        - GeospatialFilter: api_reference/geodata/coordinates_filter/geospatial_filter.md
        - MaskFilter: api_reference/geodata/coordinates_filter/mask_filter.md
        - SetFilter: api_reference/geodata/coordinates_filter/set_filter.md
      - GeodataPostprocessor:
        - GeodataPostprocessor: api_reference/geodata/geodata_postprocessor/geodata_postprocessor.md
        - ClipPostprocessor: api_reference/geodata/geodata_postprocessor/clip_postprocessor.md
        - CompositePostprocessor: api_reference/geodata/geodata_postprocessor/composite_postprocessor.md
        - FieldNamePostprocessor: api_reference/geodata/geodata_postprocessor/field_name_postprocessor.md
        - FillPostprocessor: api_reference/geodata/geodata_postprocessor/fill_postprocessor.md
        - SievePostprocessor: api_reference/geodata/geodata_postprocessor/sieve_postprocessor.md
        - SimplifyPostprocessor: api_reference/geodata/geodata_postprocessor/simplify_postprocessor.md
        - ValuePostprocessor: api_reference/geodata/geodata_postprocessor/value_postprocessor.md
      - GridGenerator: api_reference/geodata/grid_generator.md
    - aviary.inference:
      - Exporter:
        - Exporter: api_reference/inference/exporter/exporter.md
        - SegmentationExporter: api_reference/inference/exporter/segmentation_exporter.md
      - Model:
        - Model: api_reference/inference/model/model.md
        - SegmentationModel: api_reference/inference/model/segmentation_model.md
        - ONNXSegmentationModel: api_reference/inference/model/onnx_segmentation_model.md
    - aviary.pipeline:
      - PostprocessingPipeline: api_reference/pipeline/postprocessing_pipeline.md
      - SegmentationPipeline: api_reference/pipeline/segmentation_pipeline.md
  - CLI Reference:
      - CLI Reference: cli_reference/index.md
      - Segmentation pipeline: cli_reference/segmentation_pipeline.md
      - Postprocessing pipeline: cli_reference/postprocessing_pipeline.md
  - Aviary:
      - Aviary: aviary/index.md

theme:
  name: material
  custom_dir: ../docs/overrides
  language: en
  logo_light_mode: assets/aviary_logo_black.svg
  logo_dark_mode: assets/aviary_logo_white.svg
  favicon: assets/aviary_logo_white.svg
  font:
    text: Noto Sans
    code: Noto Sans Mono
  icon:
    repo: simple/github
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.top
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: white
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

plugins:
  - privacy
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            show_root_full_path: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: source
            docstring_style: google
            docstring_section_style: spacy
            merge_init_into_class: true
            annotations_path: source
            show_signature: false
          paths:
            - ../

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra:
  generator: false
  social:
    - icon: simple/github
      link: https://github.com/geospaitial-lab
    - icon: simple/huggingface
      link: https://huggingface.co/geospaitial-lab

extra_css:
  - stylesheets/color.css
  - stylesheets/extra.css

copyright:
  © 2024 geospaitial lab
